language: python
python:
  - "3.5"
  - "3.6"
before_script:
  - "pip install mock"
  - "pip install 'coverage<4'"
  - "pip install pytest pytest-cov codacy-coverage"
install: "pip install ."
# command to run tests
script: "pytest --cov boss --cov-report xml tests"
after_success:
  - "python-codacy-coverage -r coverage.xml"