language: python
python:
  - "3.5"
  - "3.6"
before_script:
  - "pip install mock"
  - "pip install 'coverage<4'"
  - "pip install pytest pytest-cov python-coveralls"
install: "pip install ."
# command to run tests
script: "py.test --cov boss --cov-report term-missing tests"
after_success:
  - "coveralls"